// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxs96VfgRX2XZvdFmqg-P6ZbiemMGGqlM',
    appId: '1:259812401210:web:300441d43fc52457b41503',
    messagingSenderId: '259812401210',
    projectId: 'mydiary-d86fc',
    authDomain: 'mydiary-d86fc.firebaseapp.com',
    storageBucket: 'mydiary-d86fc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxs96VfgRX2XZvdFmqg-P6ZbiemMGGqlM',
    appId: '1:259812401210:web:4d614018e837d76fb41503',
    messagingSenderId: '259812401210',
    projectId: 'mydiary-d86fc',
    authDomain: 'mydiary-d86fc.firebaseapp.com',
    storageBucket: 'mydiary-d86fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-SZXXN82nj64Yh_kc57xCu_5Mu7r5uto',
    appId: '1:259812401210:android:e6acd64400c76c7bb41503',
    messagingSenderId: '259812401210',
    projectId: 'mydiary-d86fc',
    storageBucket: 'mydiary-d86fc.firebasestorage.app',
  );

}